# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hypersheets',
                'doc_host': 'https://KGrewal1.github.io',
                'git_url': 'https://github.com/KGrewal1/hypersheets',
                'lib_path': 'hypersheets'},
  'syms': {'hypersheets.core': {'hypersheets.core.foo': ('core.html#foo', 'hypersheets/core.py')}}}