# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hypersheets',
                'doc_host': 'https://KGrewal1.github.io',
                'git_url': 'https://github.com/KGrewal1/hypersheets',
                'lib_path': 'hypersheets'},
  'syms': { 'hypersheets.core': {'hypersheets.core.foo': ('core.html#foo', 'hypersheets/core.py')},
            'hypersheets.stats': { 'hypersheets.stats.comp': ('stats.html#comp', 'hypersheets/stats.py'),
                                   'hypersheets.stats.compsum': ('stats.html#compsum', 'hypersheets/stats.py'),
                                   'hypersheets.stats.expected_return': ('stats.html#expected_return', 'hypersheets/stats.py'),
                                   'hypersheets.stats.foo': ('stats.html#foo', 'hypersheets/stats.py'),
                                   'hypersheets.stats.geometric_mean': ('stats.html#geometric_mean', 'hypersheets/stats.py'),
                                   'hypersheets.stats.ghpr': ('stats.html#ghpr', 'hypersheets/stats.py')}}}