# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_stats.ipynb.

# %% auto 0
__all__ = ['compsum', 'foo']

# %% ../nbs/00_stats.ipynb 4
def compsum(returns):
    """Calculates rolling compounded returns"""
    return returns.add(1).cumprod() 

# %% ../nbs/00_stats.ipynb 6
def foo(): pass
