# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_utils.ipynb.

# %% auto 0
__all__ = ['mtd', 'qtd']

# %% ../nbs/00_utils.ipynb 3
def mtd(df):
    """Restrict a dataframe to only month to date"""
    return df[df.index >= _dt.datetime.now(
    ).strftime('%Y-%m-01')]

# %% ../nbs/00_utils.ipynb 4
def qtd(df):
    """Restrict a dataframe to only quarter to date (quarters starting in Jan, Apr, Jun, Oct) """
    return df[df.index >= _dt.datetime.now(
    ).strftime('%Y-%m-01')]
